name: talent_assessment
description: AI-powered athletic talent assessment app
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Essential Dependencies Only
  firebase_core: ^2.27.0
  firebase_auth: ^4.17.8
  cloud_firestore: ^4.15.8
  
  # Camera & Video
  camera: ^0.10.6
  video_player: ^2.8.2
  image_picker: ^1.0.4
  
  # Local Storage (simplified - no SQLite for now)
  shared_preferences: ^2.2.3
  
  # State Management
  provider: ^6.1.2
  
  # UI
  fl_chart: ^0.68.0
  
  # Utilities
  path_provider: ^2.1.3
  permission_handler: ^11.3.1
  
  cupertino_icons: ^1.0.2
  google_mlkit_pose_detection: ^0.12.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  
  # Remove or comment out assets section until you need it
  # assets:
  #   - assets/images/
  #   - assets/data/