// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCOO2HEsK2jL31tMFdilkOEZfmfPr-_V4U',
    appId: '1:114085549265:web:b8401a538a17297cd9a1f0',
    messagingSenderId: '114085549265',
    projectId: 'talent-assessment-b38bf',
    authDomain: 'talent-assessment-b38bf.firebaseapp.com',
    storageBucket: 'talent-assessment-b38bf.firebasestorage.app',
    measurementId: 'G-2DWFHJRP2R',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAxulB2LH5uXrUYrS_AQt_LEGXpMhBm-CI',
    appId: '1:114085549265:android:ab4876689089b63bd9a1f0',
    messagingSenderId: '114085549265',
    projectId: 'talent-assessment-b38bf',
    storageBucket: 'talent-assessment-b38bf.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDZ7WPeo6wjekAko3S733ZNu7m3DaC8odc',
    appId: '1:114085549265:ios:f82c1d700d8067a5d9a1f0',
    messagingSenderId: '114085549265',
    projectId: 'talent-assessment-b38bf',
    storageBucket: 'talent-assessment-b38bf.firebasestorage.app',
    iosBundleId: 'com.example.talentAssessment',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDZ7WPeo6wjekAko3S733ZNu7m3DaC8odc',
    appId: '1:114085549265:ios:f82c1d700d8067a5d9a1f0',
    messagingSenderId: '114085549265',
    projectId: 'talent-assessment-b38bf',
    storageBucket: 'talent-assessment-b38bf.firebasestorage.app',
    iosBundleId: 'com.example.talentAssessment',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCOO2HEsK2jL31tMFdilkOEZfmfPr-_V4U',
    appId: '1:114085549265:web:8d522c1ffe1c8647d9a1f0',
    messagingSenderId: '114085549265',
    projectId: 'talent-assessment-b38bf',
    authDomain: 'talent-assessment-b38bf.firebaseapp.com',
    storageBucket: 'talent-assessment-b38bf.firebasestorage.app',
    measurementId: 'G-24WYML944M',
  );

}